[consumer]
provider = "redis"
server = "localhost"
port = 6379
db = 0
password = ""

[[sync]]
  [sync.products]
    provider = "couchdb"
    server = "localhost"
    port = 5984
    username = "admin"
    password = "admin"
    database = "products"
    buffer = 1024
    interval = 5
