consumers:
  - name: redis-local
    provider: redis
    server: localhost
    port: 6379
    db: 0
    password: ""
  - name: mqtt-iotech
    provider: mqtt
    server: mq.iotech.gr
    port: 1883
    clientid: "divan"
    username: "kdihalas"
    password: "@kostas12345"
    network: "tcp"
    topic: "/env"
    buffer: 5

backends:
  - name: couchdb-local
    provider: couchdb
    server: localhost
    port: 5984
    username: admin
    password: admin
    database: products

funnels:
  - name: products
    from: redis-local
    to: couchdb-local
    buffer: 1024
    interval: 5
  - name: env
    from: mqtt-iotech
    to: couchdb-local
    buffer: 0
    interval: 5
