consumers:
  - name: redis-local
    provider: redis
    server: localhost
    port: 6379
    db: 0
    password: ""

backends:
  - name: couchdb-local
    provider: couchdb
    server: localhost
    port: 5984
    username: admin
    password: admin
    database: products

funnels:
  - name: products
    from: redis-local
    to: couchdb-local
    buffer: 1024
    interval: 5
  - name: orders
    from: redis-local
    to: couchdb-local
    buffer: 1024
    interval: 5
